import "@/styles/globals.css"

import { Inter } from "next/font/google"
import { PropsWithChildren } from "react"
import { twMerge } from "tailwind-merge"

import type { Metadata } from "next"
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Ben",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={twMerge(inter.variable, "antialiased")}>{children}</body>
    </html>
  )
}
